version: '3'
services:
  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile
        args:
          REACT_APP_API_URL: /api
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
  backend:
    build: ./backend
    ports:
      - "3004:3004" 
    environment:
      MONGODB_URI: mongodb://mongo:27017/confectioneryDB 
    restart: always
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 
    volumes:
      - mongo-db:/data/db
      - ./backend/confectioneryDB.vacancies.json:/data/db/confectioneryDB.vacancies.json
      - ./backend/confectioneryDB.products.json:/data/db/confectioneryDB.products.json
    restart: always
volumes:
  mongo-db:
