version: '3'
services:
  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile
        args:
          REACT_APP_API_URL: /api
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always
  backend:
    build: ./backend
    environment:
      MONGODB_URI: mongodb://mongo:27017/confectioneryDB 
    restart: always
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
volumes:
  mongo-db:
