version: '3'

services:
  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile
        args:
          REACT_APP_API_URL: /api
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always
    networks:
      - frontend
  backend:
    build: ./backend
    environment:
      MONGODB_URI: mongodb://mongo:27017/confectioneryDB 
    restart: always
    networks:
      - frontend
      - backend
  mongo:
    image: mongo:latest
    volumes:
      - mongo-db:/data/db
      - ./backend/confectioneryDB.vacancies.json:/data/db/confectioneryDB.vacancies.json
      - ./backend/confectioneryDB.products.json:/data/db/confectioneryDB.products.json
    restart: always
    networks:
      - backend


networks:
  frontend:
  backend:

volumes:
  mongo-db:
